server:
  port: 8300

spring:
  application:
    name: vehicle
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-vehicle
    username: postgres
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    jpa.show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true