server:
  port: 8400

spring:
  application:
    name: parts
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-parts
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: create
    jpa.show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true